#ifndef RESQ_MBEDTLS_SHA256_WRAPPER_H
#define RESQ_MBEDTLS_SHA256_WRAPPER_H

#define MBEDTLS_DECLARE_PRIVATE_IDENTIFIERS
#include "mbedtls/private/sha256.h"
#undef MBEDTLS_DECLARE_PRIVATE_IDENTIFIERS

#endif // RESQ_MBEDTLS_SHA256_WRAPPER_H
