#ifndef SYSTEM_BUTTON_MANAGER_H
#define SYSTEM_BUTTON_MANAGER_H

#include <stdbool.h>

#include "esp_err.h"
#include "states.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    SYSTEM_BUTTON_ACTION_NONE = 0,
    SYSTEM_BUTTON_ACTION_TURN_OFF,
    SYSTEM_BUTTON_ACTION_FACTORY_RESET
} system_button_action_t;

esp_err_t system_button_manager_init(void);

/*
 * Backward-compatible API.
 *
 * Old behavior:
 *   Poll GPIO and decide long press directly.
 *
 * New behavior:
 *   Consume queued long-press actions generated by the interrupt-driven
 *   button task, then apply state safety filtering.
 */
system_button_action_t system_button_manager_poll(resq_state_t current_state);

/*
 * Optional helper for logs/tests.
 */
const char *system_button_action_to_string(system_button_action_t action);

/*
 * Drain/discard any pending queued actions. Useful when a state handles
 * buttons internally or global long-press actions should be ignored.
 */
void system_button_manager_drain_actions(resq_state_t current_state);

#ifdef __cplusplus
}
#endif

#endif
