spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resq}
    username: ${SPRING_DATASOURCE_USERNAME:resq}
    password: ${SPRING_DATASOURCE_PASSWORD:resq}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-cloud.sql
      data-locations: classpath:data-cloud.sql

logging:
  level:
    org.springframework.jdbc.core: info
