package lk.resq.localhub.model.firmware;

public enum FirmwareState {
    BOOT,
    CONFIG_CHECK,
    PROVISIONING,
    FLUSH_CONFIG,
    WIFI_CONNECTING,
    BACKEND_REGISTERING,
    MQTT_CONNECTING,
    PAIRED_IDLE,
    CALIBRATING,
    CALIBRATION_FAIL,
    READY_FOR_SESSION,
    SESSION_ACTIVE,
    SESSION_INTERRUPTED,
    ERROR,
    RESETTING,
    TURN_OFF
}